name: Create Production Builds

on:
  push:
    branches: ["master"]

jobs:
  build_android:
    name: Build Android APK
    type: build
    params:
      platform: android
      profile: production

  build_android_aab:
    name: Build Android AAB
    type: build
    params:
      platform: android
      profile: production-aab
